Teamworks/ASP.NETN MVC/EbayApplication/EbayApplication.Web/Models/AuctionModels/AuctionViewModel.cs
namespace EbayApplication.Web.Models.AuctionModels
{
    using System;

    public class AuctionViewModel
    {
        public Guid Id { get; set; }

        public DateTime ExpiringDate { get { return this.DateStarted.AddMinutes(this.Duration); } }

        public string ProductName { get; set; }

        public int Duration { get; set; }

        public DateTime DateStarted { get; set; }
    }
}

Teamworks/ASP.NETN MVC/EbayApplication/EbayApplication.Web/Controllers/AuctionsController.cs
namespace EbayApplication.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;
    using EbayApplication.Models;
    using EbayApplication.Repositories;
    using EbayApplication.Web.Models.UserModels;
    using System.Globalization;
    using EbayApplication.Web.Models.AuctionModels;
    using EbayApplication.Web.Models.ProductModels;
    using Microsoft.AspNet.Identity;

    [Authorize]
    public class AuctionsController : Controller
    {
        private IUnitOfWorkData db;

        public AuctionsController(IUnitOfWorkData db)
        {
            this.db = db;
        }

        public AuctionsController()
        {
            this.db = new UnitOfWorkData();
        }

        [HttpGet]
        public ActionResult Create()
        {
            string loggedUserId = User.Identity.GetUserId();

            ApplicationUser currentUser = this.db.Users.All().FirstOrDefault(user => user.Id == loggedUserId);

            if (currentUser == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "User not found");
            }

            var ownProducts = this.db.Products
                                            .All()
                                            .Where(product => product.Owner.Id == currentUser.Id)
                                            .ToList()
                                            .Select(productEntity => new SelectListItem () 
                                            {
                                                Text = productEntity.Title,
                                                Value = productEntity.Id.ToString()
                                            });

            ViewBag.OwnProducts = ownProducts;

            return View();
        }

        public ActionResult ByUser()
        {
            string userId = User.Identity.GetUserId();

            ApplicationUser currentUser = this.db.Users.All().FirstOrDefault(user => user.Id == userId);

            if (currentUser == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "User doesn't exist");
            }

            IEnumerable<AuctionDetailedViewModel> auctions =
                    from auctionEntity in currentUser.CurrentAuctions
                    select new AuctionDetailedViewModel
                    {
                        Id = auctionEntity.Id,
                        ProductName = auctionEntity.Product.Title,
                        DateStarted = auctionEntity.DateStarted,
                        Product = ProductViewModel.CreateFromProduct(auctionEntity.Product),
                        CurrentBuyer = auctionEntity.CurrentBuyer,
                        Duration = auctionEntity.Duration
                    };
                    

            return View(auctions);
        }

        [HttpPost, ValidateAntiForgeryToken, ValidateInput(true)]
        [Authorize]
        public ActionResult Create(AuctionCreateModel model)
        {
            string loggedUserId = User.Identity.GetUserId();

            ApplicationUser currentUser = this.db.Users.GetById(loggedUserId);

            if (ModelState.IsValid)
            {

                Product currentProduct = this.db.Products.All().FirstOrDefault(product => product.Id == model.ProductId);

                Auction newAuction = this.db.Auctions.All().FirstOrDefault(auction => auction.Product.Id == model.ProductId);

                if (newAuction != null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "There is already an auction for this product");
                }

                newAuction = new Auction
                {
                    Id = Guid.NewGuid(),
                    DateStarted = DateTime.Now,
                    Duration = model.Duration,
                    Product = currentProduct,
                    Type = model.Type,
                    CurrentPrice = currentProduct.StartingPrice
                };

                this.db.Auctions.Add(newAuction);
                this.db.SaveChanges();

                return RedirectToAction("Details", "Products", new { id = currentProduct.Id });
            }

            var ownProducts = this.db.Products
                                          .All()
                                          .Where(product => product.Owner.Id == currentUser.Id)
                                          .ToList()
                                          .Select(productEntity => new SelectListItem()
                                          {
                                              Text = productEntity.Title,
                                              Value = productEntity.Id.ToString()
                                          });

            ViewBag.OwnProducts = ownProducts;

            return View();
        }

        [Authorize]
        public ActionResult Current(Guid? productId)
        {
            if (productId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Auction currentAuction = this.db.Auctions.All().Include("Product").FirstOrDefault(auction => auction.Product.Id == productId);

            if (currentAuction == null)
            {
                return Content("There isn't auction for this product any more. Please stay tuned up, for new auctions :)");
            }

            if (DateTime.Compare(currentAuction.DateStarted.AddMinutes(currentAuction.Duration), DateTime.Now) < 0)
            {
                this.db.Auctions.Delete(currentAuction);
                this.db.SaveChanges();

                return Content("There isn't auction for this product any more. Please stay tuned up, for new auctions :)");
            }
            else
            {
                AuctionDetailedViewModel model = new AuctionDetailedViewModel
                {
                    Id = currentAuction.Id,
                    CurrentPrice = currentAuction.CurrentPrice,
                    DateStarted = currentAuction.DateStarted,
                    Product = ProductViewModel.CreateFromProduct(currentAuction.Product),
                    Type = currentAuction.Type,
                    Duration = currentAuction.Duration,
                    CurrentBuyer = currentAuction.CurrentBuyer
                };

                return View(model);
            }
        }

        [Authorize]
        public ActionResult Bid(UserBetModel currentBet)
        {
            if(ModelState.IsValid == false)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            string userId = User.Identity.GetUserId();

            ApplicationUser currentUser = this.db.Users.All().FirstOrDefault(user => user.Id == userId);

            Auction currentAuction = this.db.Auctions.All().FirstOrDefault(auction => auction.Id == currentBet.AuctionId);

            if (currentAuction == null || currentUser == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "User or auction doesn't exist.");
            }

            if (currentAuction.Type != AuctionType.Auction)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "This isn't an auction");
            }

            //if (currentAuction.CurrentBuyer == User.Identity.GetUserName())
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "You are already current buyer.");
            //}

            if (currentAuction.CurrentPrice >= currentBet.OfferedPrice)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest,
                    string.Format("You have to offer more than {0}.",
                        currentAuction.CurrentPrice.ToString("f2", CultureInfo.InvariantCulture)));
            }

            if (DateTime.Compare(DateTime.Now, currentAuction.DateStarted.AddMinutes(currentAuction.Duration)) > 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Auction already expired.");
            }
            
            Product currentProduct = db.Products.All().FirstOrDefault(product => product.Id == currentAuction.Product.Id);

            currentAuction.Product = currentProduct;
            currentAuction.CurrentBuyer = currentUser.UserName;
            currentAuction.CurrentPrice = currentBet.OfferedPrice;
            currentAuction.ParticipatingUsers.Add(currentUser);
            currentUser.CurrentAuctions.Add(currentAuction);

            this.db.Auctions.Update(currentAuction);
            this.db.Users.Update(currentUser);
            this.db.SaveChanges();


            return PartialView("_Auction", AuctionDetailedViewModel.CreateFromAuction(currentAuction));
        }

        [Authorize]
        public ActionResult GetCurrentBid(Guid? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Auction currentAuction = this.db.Auctions.All().FirstOrDefault(auction => auction.Id == id);

            if (currentAuction == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "User or auction doesn't exist.");
            }


            return PartialView("_BaseAuction", AuctionDetailedViewModel.CreateFromAuction(currentAuction));
        }

        [Authorize]
        public ActionResult Buy(Guid? id)
        {

            string userId = User.Identity.GetUserId();

            Auction currentAuction = this.db.Auctions.All().FirstOrDefault(auction => auction.Id == id);

            ApplicationUser currentUser = this.db.Users.All().FirstOrDefault(user => user.Id == userId);

Teamworks/ASP.NETN MVC/EbayApplication/EbayApplication.Web/Controllers/ShoppingCartController.cs
namespace EbayApplication.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;
    using Microsoft.AspNet.Identity;
    using EbayApplication.Models;
    using EbayApplication.Repositories;
    using EbayApplication.Web.Models.AuctionModels;

    [Authorize]
    public class ShoppingCartController : Controller
    {
        private IUnitOfWorkData db;

        public ShoppingCartController(IUnitOfWorkData db)
        {
            this.db = db;
        }

        public ShoppingCartController()
        {
            this.db = new UnitOfWorkData();
        }

        public ActionResult ByUser()
        {
            string loggedUserId = User.Identity.GetUserId();

            ApplicationUser currentUser = this.db.Users.All().FirstOrDefault(user => user.Id == loggedUserId);

            if (currentUser == null)
            {
                  return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "User not found.");
            }

            IEnumerable<AuctionViewModel> model =
                from auctionEntity in currentUser.ShoppingCart.Auctions
                select new AuctionViewModel()
                {
                    DateStarted =  auctionEntity.DateStarted,
                    Duration = auctionEntity.Duration,
                    ProductName = auctionEntity.Product.Title,
                    Id = auctionEntity.Id
                };


            return View(model);
        }

        public ActionResult BuyProducts()
        {
            var user = this.db.Users.GetById(User.Identity.GetUserId());
            
            var shoppingCartId = user.ShoppingCart.Id;

            if (shoppingCartId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Id is required");
            }

            ShoppingCart currentCart = this.db.ShoppingCarts.All().FirstOrDefault(cart => cart.Id == shoppingCartId);

            if (currentCart == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Shopping cart, not found.");
            }

            if (currentCart.Auctions.Count == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Cart is empty.");
            }

            int deliveryDurationTime = 0;

            Delivery createdDelivery = new Delivery
            {
                Id = Guid.NewGuid(),
                DateShipped = DateTime.Now,
                Receiver = currentCart.Owner,
                State = DeliveryState.Shipping
            };

            int count = currentCart.Auctions.Count;

            foreach (Auction currentAuction in currentCart.Auctions.ToList())
            {
                createdDelivery.Products.Add(currentAuction.Product);

                deliveryDurationTime += currentAuction.DeliveryDuration;

                this.db.Auctions.Delete(currentAuction);

            }

            int time = deliveryDurationTime / count;

            createdDelivery.Duration = time;

            currentCart.Auctions.Clear();
            
            this.db.ShoppingCarts.Update(currentCart);

            this.db.Deliveries.Add(createdDelivery);
            
            this.db.SaveChanges();

            return Content("Products are shipped");
        }

        public ActionResult AddToShoppingCart(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Id is required");
            }

            Auction currentAuction = this.db.Auctions.All().FirstOrDefault(auction => auction.Id == id);

            string loggedUserId = User.Identity.GetUserId();

            ApplicationUser currentUser = this.db.Users.All().FirstOrDefault(user => user.Id == loggedUserId);

            ShoppingCart currentCart = currentUser.ShoppingCart;

            currentAuction.ShoppingCarts.Add(currentCart);

            currentCart.Auctions.Add(currentAuction);

            this.db.Auctions.Update(currentAuction);

            this.db.ShoppingCarts.Update(currentCart);

            this.db.SaveChanges();

            return Content("Product successfully added to shopping cart.");
        }

        public ActionResult RemoveFromShoppingCart(Guid? id)
        {
            string loggedUserId = User.Identity.GetUserId();

            if(loggedUserId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "You should be logged.");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Product id is required.");
            }

            ApplicationUser currentUser = this.db.Users.GetById(loggedUserId);

            if (currentUser == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "User not found.");
            }

            ShoppingCart currentCart = currentUser.ShoppingCart;

            Auction currentAuction = this.db.Auctions.GetById(id);

            if (currentAuction == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Auction not found.");
            }

            if (currentCart.Auctions.Contains(currentAuction) == false)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Auction is not in this cart.");
            }

            currentCart.Auctions.Remove(currentAuction);

            currentAuction.ShoppingCarts.Remove(currentCart);

            this.db.Auctions.Update(currentAuction);

            this.db.ShoppingCarts.Update(currentCart);

            this.db.SaveChanges();

            return this.Content("Auction removed successfully.");
        }
	}
}

Teamworks/ASP.NETN MVC/EbayApplication/EbayApplication.Web/Views/Shared/_Auction.cshtml
@model EbayApplication.Web.Models.AuctionModels.AuctionDetailedViewModel

@if (DateTime.Compare(Model.ExpiringDate, DateTime.Now) > 0)
{

<strong>Current price: @Model.CurrentPrice </strong><br />

    if (Model.CurrentBuyer != User.Identity.Name)
    {
        using (Ajax.BeginForm("Bid", "Auctions", null,
                        new AjaxOptions()
                        {
                            HttpMethod = "POST",
                            UpdateTargetId = "auction-panel",
                            InsertionMode = InsertionMode.Replace
                        }))
        {
            @Html.TextBox("OfferedPrice", (int)@Model.CurrentPrice + 1 ,  new { @type="number", pattern=@"\d*", step="1" })
            @Html.Hidden("AuctionId", Model.Id)
    
           <input type="submit" class="btn btn-primary" value="Bid"/>
        }
    }
    
     

}
else
{
    if (Model.CurrentBuyer == User.Identity.Name)
    {
        @Ajax.ActionLink(
                    "Get the product", "CloseAuction", "Auctions", 
                    new { @id = Model.Id }, 
                    new AjaxOptions() { UpdateTargetId="window", InsertionMode = InsertionMode.Replace, OnSuccess="displayWindow" }, 
                    new { @class = "btn btn-success" }
        );
    
        <div id="window" style="display:none">

        </div>
    }
    else
    {
        <p>There isn't auction for this product</p>
    }
}

Teamworks/ASP.NETN MVC/EbayApplication/EbayApplication.Web/Views/Shared/_BaseAuction.cshtml
@model EbayApplication.Web.Models.AuctionModels.AuctionDetailedViewModel

@if (this.ViewContext.FormContext == null)
{
    this.ViewContext.FormContext = new FormContext();
}

<div id="auction-panel" class="well pull-left">


    @if (@Model.Type == EbayApplication.Models.AuctionType.Normal)
    {
        @Html.Partial("_NormalAuction", Model);
       
    }
    else
    {
        @Html.Partial("_Auction", Model);
    
    }

</div>

<script>

    //CountDownTimer('@Model.ExpiringDate.ToString("MM/dd/yyyy H:m ", System.Globalization.CultureInfo.InvariantCulture)', 'countdown');

    function CountDownTimer(dt, id) {
        var end = new Date(dt);

        var _second = 1000;
        var _minute = _second * 60;
        var _hour = _minute * 60;
        var _day = _hour * 24;
        var timer;

        function showRemaining() {
            var now = new Date();
            var distance = end - now;
            if (distance < 0) {

                clearInterval(timer);
                document.getElementById(id).innerHTML = 'EXPIRED!';

                return;
            }
            var days = Math.floor(distance / _day);
            var hours = Math.floor((distance % _day) / _hour);
            var minutes = Math.floor((distance % _hour) / _minute);
            var seconds = Math.floor((distance % _minute) / _second);

            document.getElementById(id).innerHTML = days + 'days ';
            document.getElementById(id).innerHTML += hours + 'hrs ';
            document.getElementById(id).innerHTML += minutes + 'mins ';
            document.getElementById(id).innerHTML += seconds + 'secs';
        }

        timer = setInterval(showRemaining, 1000);
    }

</script>


<script>


    function displayWindow() {
        $("#window").show();

        var window = $("#window");

        if (!window.data("kendoWindow")) {
            var messageWindow = window.kendoWindow({
                width: "300px",
                height: "200px",
                title: "Message",
                resizable: false,
                draggable: false,
                actions: {},
                close: updatePage
            }).data("kendoWindow");

            messageWindow.center();
        }
    }


    $("#window-close-button").on("click", function () {
        var window = $("#window").data("kendoWindow");

        window.close();
    });

    function updatePage() {
        document.location.href="/Delivery/ByUser?username=@User.Identity.Name";
    }
</script>

Teamworks/ASP.NETN MVC/EbayApplication/EbayApplication.Web/Views/Shared/_DeliveriesByUser.cshtml
@model IEnumerable<EbayApplication.Web.Models.DeliveryModels.DeliveryViewModel>

<table class="table">
    <thead>
        <tr>
            <th>Number</th>

            <th>State</th>

            <th>Time to arrive</th>
        </tr>
    </thead>

    <tbody>

        @foreach (EbayApplication.Web.Models.DeliveryModels.DeliveryViewModel currentDelivery in Model)
        {
            <tr>
                <td>@currentDelivery.Id.ToString().Substring(24, 7)</td>
                <td>@currentDelivery.State</td>
                <td>@currentDelivery.TimeToArrive.ToString("dd-MMM-yyyy  HH:mm", System.Globalization.CultureInfo.InvariantCulture)</td>
                @if (currentDelivery.State == EbayApplication.Models.DeliveryState.Delivered)
                {
                    <td><button disabled="disabled" class="btn btn-success">Delivered</button></td>
                }
                else
                {
                    <td>@Ajax.ActionLink("Check package", "CloseDelivery", 
                            new { @id = currentDelivery.Id }, 
                            new AjaxOptions() { 
                                InsertionMode = InsertionMode.Replace,
                                UpdateTargetId = "window-message",
                                OnComplete = "displayWindow"}, 
                            new { @class = "btn btn-warning" }) 
                    </td>
                }
            </tr>
        }

    </tbody>
</table>

Teamworks/ASP.NETN MVC/EbayApplication/EbayApplication.Web/Views/Shared/_Details.cshtml
@model EbayApplication.Web.Models.ProductModels.ProductViewModel

<div id="picture-modal" class="modal hide fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: none">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">@Model.Title</h3>
    </div>
    <div class="modal-body text-center">
        <img src="~/img/products/@Model.ImageUrl" width="400" height="400" />
    </div>
    <div class="modal-footer">
        <button type="button" data-dismiss="modal" aria-hidden="true" class="btn btn-primary">Close</button>
    </div>
</div>

<div class="row-fluid">
    <fieldset>
        <div class="span3">
            <div class="thumbnail">
                <a data-toggle="modal" href="#picture-modal">
                    <img alt="300x200" style="width: 300px; height: 200px;" src="~/img/products/@Model.ImageUrl">
                </a>
            </div>
        </div>

        <div class="span9">
            <div>
                <b>@Html.DisplayFor(model => model.Title)</b>
            </div>
            <hr />

            <div>
                Item Condition:  <b>@Html.DisplayFor(model => model.Condition)</b>
            </div>

            <div class="container">
                <div class="span5">
                    <div>Price: @Html.DisplayFor(model => model.Price)</div>
                </div>
            </div>

            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.StartingPrice)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.StartingPrice)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DateAdded)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateAdded)
                </dd>
            </dl>
        </div>
    </fieldset>
</div>

Teamworks/ASP.NETN MVC/EbayApplication/EbayApplication.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/kendo")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/unobtrusive")
    @Scripts.Render("~/bundles/kendo")
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Medusa's Ebay", "Index", "Home", null, new { @class = "brand" })

                @if (User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Admin", "Index", "Admin/AdminHome", null, new { @class = "brand" })
                }
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Summary
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                    <li>
                                        <a href="~/Delivery/ByUser">Deliveries</a>
                                    </li>
                                        <li>
                                        <a href="~/Auctions/ByUser">Auctions</a>
                                    </li>
                                        <li>
                                        <a href="~/Funds/ByUser">Withdraws</a>
                                    </li>
                            </ul>
                          </li>
                        }

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Products
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="~/Products/All">All Products</a></li>

                                @if (User.Identity.IsAuthenticated)
                                {
                                    <li>@Html.ActionLink("My products", "ByUser", "Products", null, null)</li>
                                    <li>@Html.ActionLink("Sell products", "Create", "Auctions",null, null)</li>
                                     <li><a href="~/Products/Create">Add Product</a></li>
                                }
                            </ul>

                            
                        </li>

                        <li>
                            @if (User.Identity.IsAuthenticated) {
                                @Html.ActionLink("My cart", "ByUser", "ShoppingCart", null, null);
                            }
                        </li>

                        <li>
                            @using (Html.BeginForm("Search", "Products", FormMethod.Get))
                            {
                                @(Html.Kendo().AutoComplete()
                                .Name("product")
                                .DataTextField("Title")
                                .MinLength(3)
                                .HtmlAttributes(new { style = "width:250px" })
                                .Placeholder("Search product")
                                .DataSource(source =>
                                {
                                    source.Read(read =>
                                    {
                                        read.Action("GetProducts", "Products")
                                            .Data("onAdditionalData");
                                    })
                                    .ServerFiltering(true);
                                })
                                )

                                <button id="btn-search" class="btn btn-success" type="submit">
                                    <i class="icon-search"></i>
                                    Search
                                </button>
                            }
                        </li>
                    </ul>

                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        function onAdditionalData() {
            return {
                text: $("#product").val()
            };
        }

        $(document).ready(function () {
            $("#nav-menu").kendoMenu();
        });
    </script>
</body>
</html>

Teamworks/ASP.NETN MVC/EbayApplication/EbayApplication.Web/Views/Shared/_NormalAuction.cshtml
@model EbayApplication.Web.Models.AuctionModels.AuctionDetailedViewModel

@Ajax.ActionLink("Buy it now", "Buy", "Auctions", new { id = Model.Id }, new AjaxOptions {
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "window-message",
    OnSuccess = "displayWindow"}, new { @class = "btn btn-success" }) 

@Ajax.ActionLink("Add to shopping cart", "AddToShoppingCart", "ShoppingCart", new { id = Model.Id }, new AjaxOptions
{
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "window-message",
    OnSuccess = "displayWindow"
}, new { @class = "btn btn-success" }) 

<div id="window" style="display:none">
    <p id="window-message"></p>
    <input type="button" class="btn btn-success" id="window-close-button" value="Okay" />
</div>